version: "3"

tasks:
  build:
    cmds:
      - docker compose build
  
  run:
    cmds:
      - docker compose run --rm --service-ports api

  bash:
    cmds:
      - docker compose run --rm api bash